steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:2.2'
  entrypoint: 'sh'
  args: ['script/install']

- name: 'mcr.microsoft.com/dotnet/core/sdk:2.2'
  entrypoint: 'sh'
  args: ['script/test']

- name: 'mcr.microsoft.com/dotnet/core/sdk:2.2'
  entrypoint: 'sh'
  args: ['script/build']

- name: 'mcr.microsoft.com/dotnet/core/sdk:2.2'
  entrypoint: 'sh'
  args: ['script/package']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-two-209503/vips-api']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'vips-api', '--image', 'gcr.io/project-two-209503/vips-api', '--region', 'australia-southeast1']

images:
- gcr.io/project-two-209503/vips-api
