steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['sh', 'script/install']

- name: 'gcr.io/cloud-builders/dotnet'
  args: ['sh', 'script/test']

- name: 'gcr.io/cloud-builders/dotnet'
  args: ['sh', 'script/build']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-two-209503/vips-api']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'vips-api', '--image', 'gcr.io/project-two-209503/vips-api', '--region', 'australia-southeast1']

images:
- gcr.io/project-two-209503/vips-api
