#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# --------

export REPO_NAME="gcr.io/project-two-209503/vips-api"

docker deploy push $REPO_NAME

gcloud beta run deploy vips-api \
  --image $REPO_NAME \
  --region us-central1
